### ISSUE TITLE
Errors out with WindowsError: [Error 5] Access Denied: '/Users/sundeepblue'

### ISSUE THREAD

**Issue by tensigh** [sundeepblue/movie_rating_prediction#1]
Hello, you have your directory hard coded in settings.py and parse_scraped_data.py. If you changed them to "./movie", it worked. Just thought it might come in handy. Otherwise, cool spider!

**Comment by rolandon** [comment]
@tensigh i am getting the below error. do you have any experience coding?


MacBook-Air:movie mac$ scrapy crawl movie_budget -o movie_budget.json
Traceback (most recent call last):
File "/Users/mac/anaconda/bin/scrapy", line 6, in 
sys.exit(scrapy.cmdline.execute())
File "/Users/mac/anaconda/lib/python3.6/site-packages/scrapy/cmdline.py", line 109, in execute
settings = get_project_settings()
File "/Users/mac/anaconda/lib/python3.6/site-packages/scrapy/utils/project.py", line 68, in get_project_settings
settings.setmodule(settings_module_path, priority='project')
File "/Users/mac/anaconda/lib/python3.6/site-packages/scrapy/settings/init.py", line 292, in setmodule
module = import_module(module)
File "/Users/mac/anaconda/lib/python3.6/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 978, in _gcd_import
File "", line 961, in _find_and_load
File "", line 936, in _find_and_load_unlocked
File "", line 205, in _call_with_frames_removed
File "", line 978, in _gcd_import
File "", line 961, in _find_and_load
File "", line 950, in _find_and_load_unlocked
File "", line 655, in _load_unlocked
File "", line 674, in exec_module
File "", line 888, in get_code
File "", line 455, in _validate_bytecode_header
ImportError: bad magic number in 'movie': b'\x03\xf3\r\n'

**Comment by tensigh** [comment]
Do you have a .pyc file in the same directory? Delete it or move it and try running the spider again.

**Comment by rolandon** [comment]
hello Tensigh, thanks for responding
I have a few .PYC files in the new project folder. i listed below
_init_.pyc
items.pyc
settings.pyc

I also have a spiders folder

**Comment by tensigh** [comment]
@rolandon I would suggest moving those .pyc files out of the directory you're working in and then try running your spider again. The .pyc files will be rebuilt when the spider is rerun.
