### ISSUE TITLE
ImportError: bad magic number in 'movie': b'\x03\xf3\r\n'

### ISSUE THREAD

**Issue by rolandon** [sundeepblue/movie_rating_prediction#2]
Hello @sundeepblue 
would you be able to help me with the below error? i have never coded before and working on a project to do exactly what you have achieved here. When you a moment can you assist?

MacBook-Air:movie mac$ scrapy crawl movie_budget -o movie_budget.json
Traceback (most recent call last):
  File "/Users/mac/anaconda/bin/scrapy", line 6, in <module>
    sys.exit(scrapy.cmdline.execute())
  File "/Users/mac/anaconda/lib/python3.6/site-packages/scrapy/cmdline.py", line 109, in execute
    settings = get_project_settings()
  File "/Users/mac/anaconda/lib/python3.6/site-packages/scrapy/utils/project.py", line 68, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/Users/mac/anaconda/lib/python3.6/site-packages/scrapy/settings/__init__.py", line 292, in setmodule
    module = import_module(module)
  File "/Users/mac/anaconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 888, in get_code
  File "<frozen importlib._bootstrap_external>", line 455, in _validate_bytecode_header
ImportError: bad magic number in 'movie': b'\x03\xf3\r\n'

**Comment by saiprasathgopinathan** [comment]
Delete the .PyC files and try the executing
